apiVersion: apiextensions.k8s.io/v1  
kind: CustomResourceDefinition 
metadata: 
  name: grafana.cogno.org 
spec: 
  scope: Namespaced 
  group: cogno.org 
  versions: 
    - name: v1 
      served: true 
      storage: true 
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                nodeport:
                  type: integer
  names: 
    kind: Grafana 
    plural: grafana 
    singular: grafana 
    shortNames: 
      - gf 
      - gfn 